In [4]:
import pandas as pd
from datetime import datetime
import os

df_init = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\cfm-nlp\Automation.xlsx", sheet_name='IIP edit')

path_dict = dict()
list_1 = ['IMF IIP Annual.xlsx', 'IMF IIP Quarterly.xlsx']
# directory_path= r'C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data'
directory_path= r'C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data'
for filename in os.listdir(directory_path):
    if filename in ['01 Emerging Market', '02 G7 Countries']:
        continue
    file_path = os.path.join(directory_path, filename)
    list_temp = []
    for filename2 in os.listdir(file_path):
        if any(word in str(filename2) for word in list_1):            
            list_temp.append(filename2)
            path_dict[filename] = list_temp
        else:
            continue

df_path = []
for k, v in path_dict.items():
    df_path.append(os.path.join(directory_path, k, v[1]))
    print(v[1]) ## to check the file name

df_all_annual = pd.DataFrame()
for x, y in enumerate(df_path):
    df = pd.read_excel(y)
    df = df[df[df.columns[0]].isin(df_init['desc'])]
    df_all_annual = pd.concat([df_all_annual, df]) 

df_all_annual.rename(columns={df_all_annual.columns[0]: 'Type'}, inplace=True)

df_all_annual_2 = df_all_annual[df_all_annual.columns[:4].to_list() + [dt for dt in df_all_annual.columns[4:].sort_values(ascending=True).to_list() if dt >= datetime(2019, 1, 1)]]

df_all_annual_2

KH IMF IIP Quarterly.xlsx
CH IMF IIP Quarterly.xlsx
HK IMF IIP Quarterly.xlsx
IN IMF IIP Quarterly.xlsx
ID IMF IIP Quarterly.xlsx
KR IMF IIP Quarterly.xlsx
MY IMF IIP Quarterly.xlsx
MG IMF IIP Quarterly.xlsx
NP IMF IIP Quarterly.xlsx
PH IMF IIP Quarterly.xlsx
SG IMF IIP Quarterly.xlsx
LK IMF IIP Quarterly.xlsx
TH IMF IIP Quarterly.xlsx

,Type,Region,Unit,Last Update Time,2019-03-01 00:00:00,2019-06-01 00:00:00,2019-09-01 00:00:00,2019-12-01 00:00:00,2020-03-01 00:00:00,2020-06-01 00:00:00,...,2023-06-01 00:00:00,2023-09-01 00:00:00,2023-12-01 00:00:00,2024-03-01 00:00:00,2024-06-01 00:00:00,2024-09-01 00:00:00,2024-12-01 00:00:00,2025-03-01 00:00:00,2025-06-01 00:00:00,2025-09-01 00:00:00
0,IIP: Assets,Cambodia,USD mn,2024-10-24,24175.971012,25075.439013,26772.011254,28628.801240,28789.701556,30657.659615,...,30053.698260,30369.724454,33601.355806,35397.755250,35803.905366,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets: Direct Investment,Cambodia,USD mn,2024-10-24,871.803862,901.219618,931.105308,951.230310,979.508508,983.442479,...,1395.942646,1419.103272,1472.557618,1505.375745,1542.416323,NaN,NaN,NaN,NaN,NaN
2,IIP: Assets: Direct Investment: Equity,Cambodia,USD mn,2024-10-24,871.803862,901.219618,931.105308,951.230310,979.508508,983.442479,...,1395.942646,1419.103272,1472.557618,1505.375745,1542.416323,NaN,NaN,NaN,NaN,NaN
5,IIP: Assets: Direct Investment: Debt Instruments,Cambodia,USD mn,2024-10-24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
9,IIP: Assets: Portfolio Investment,Cambodia,USD mn,2024-10-24,582.493802,625.895486,627.348882,583.434346,575.301891,585.633283,...,1336.049029,1389.792889,1432.075709,1316.644467,1393.873631,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,IIP: Liabilities: Other Investment: Currency &...,Thailand,USD mn,2024-10-24,4514.976301,5170.352788,5049.409806,5278.556121,5804.861421,5702.921626,...,5917.150000,6023.190000,6682.140000,6408.650000,6228.890000,NaN,NaN,NaN,NaN,NaN
163,IIP: Liabilities: Other Investment: Loans,Thailand,USD mn,2024-10-24,73138.382539,71544.286821,71760.107824,74152.075640,74158.580861,76721.524694,...,79220.680000,78472.980000,80825.270000,73014.550000,71336.830000,NaN,NaN,NaN,NaN,NaN
176,"IIP: Liabilities: Other Investment: Insurance,...",Thailand,USD mn,2024-10-24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
181,IIP: Liabilities: Other Investment: Trade Cred...,Thailand,USD mn,2024-10-24,20478.755731,20385.578822,19002.880378,18958.938449,19388.393806,19153.069679,...,27138.880000,27720.050000,27177.660000,28032.480000,27419.410000,NaN,NaN,NaN,NaN,NaN
207,IIP: Liabilities: Other Investment: SDRs,Thailand,USD mn,2024-10-24,1346.972967,1348.875505,1322.770053,1341.709178,1324.217915,1334.791182,...,5385.107004,5323.981327,5432.055277,5360.714775,5325.472939,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_init_tw = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Desktop\NLP Project\cfm-nlp\Automation.xlsx", sheet_name='Taiwan IIP')
df_tw = pd.read_excel(r"C:\Users\AhmadAizudeen\OneDrive - The SOUTH-EAST ASIAN CENTRAL BANKS (SEACEN) RESEARCH AND TRAINING\Roger and Aizudeen\Country BoP and IIP Data\Chinese Taipei (Taiwan) (TW)\TW CB IIP Annual.xlsx")
df_tw.rename(columns={df_tw.columns[0]: 'Type'}, inplace=True)
df_tw = df_tw[df_tw['Type'].isin(df_init_tw['desc'])]

for x, y in enumerate(df_tw['Type'].to_list()):
    df_tw.iat[x,0] = list(df_init_tw[(df_init_tw['desc'] == y)]['desc2'])[0]

selected_columns = [col for col in df_tw.columns[4:] if pd.to_datetime(col) >= datetime(2019, 1, 1)]
final_columns = list(df_tw.columns[:4]) + selected_columns
df_tw = df_tw[final_columns]

seacen_country = ['Papua New Guinea', 'Vietnam', 'Nepal', 'India', 'Indonesia', 'Laos', 'Sri Lanka', 'Hong Kong SAR (China)', 'Philippines', 'Taiwan', 'Malaysia', 'Mongolia', 'China', 'Cambodia', 'Thailand', 'Singapore', 'South Korea', 'Brunei', 'Myanmar']

for x in df_all_annual_2['Type'].values:
    var1 = list(set(df_all_annual_2[(df_all_annual_2['Type'] == x)]['Region'].values).symmetric_difference(set(seacen_country)))
    if len(var1) > 0:
        for y in var1:
            df_temp1 = pd.DataFrame({"Type": [x], "Region": [y]})
            df_all_annual_2 = pd.concat([df_all_annual_2, df_temp1], axis=0)
    else:
        continue

df_all_annual_2.sort_values(by=['Type', 'Region'], inplace=True)
df_all_annual_2.reset_index(drop=True, inplace=True)

init_dict = df_init.to_dict()
df_dict = dict()
for x in init_dict['desc'].values():
    df_temp = df_all_annual_2[(df_all_annual_2[df_all_annual_2.columns[0]] == x)].reset_index(drop=True)
    df_dict[x] = df_temp

# calculate the sum of the columns (1H and 2H) for each year
# num1, num2 = 0, 1
# df_col = df_all_annual_2.columns[4:][:-1]
# df_temp_col_1 = df_all_annual_2[df_all_annual_2.columns[:4]].reset_index(drop=True)

# for x in range(len(df_col)//2):
#     df_col_temp = (df_all_annual_2[df_col[num1]] + df_all_annual_2[df_col[num1 + 1]]).div(1000)
#     year = df_col[num1].year
#     df_col_temp.reset_index(drop=True, inplace=True)
#     df_temp_col_1[f'{num2}H{year}'] = df_col_temp
#     num1 += 2
#     num2 += 1
#     if num2 == 3:
#         num2 = 1

num1, num2 = 0, 1
df_col = df_all_annual_2.columns[4:][:-1]
df_temp_col_1 = df_all_annual_2[df_all_annual_2.columns[:4]].reset_index(drop=True)

for x in range(len(df_col)//2):
    df_col_temp = (df_all_annual_2[df_col[num1]] + df_all_annual_2[df_col[num1 + 1]]).div(1000)
    year = df_col[num1].year
    df_col_temp.reset_index(drop=True, inplace=True)
    df_temp_col_1[f'{num2}H{year}'] = df_col_temp
    num1 += 2
    num2 += 1
    if num2 == 3:
        num2 = 1

df_temp_col_1.drop(columns=['Last Update Time', 'Unit'], inplace=True)

calc_dict = {'Asia-Pacific': seacen_country,
            'Asian Advance Economies': ['Hong Kong SAR (China)', 'South Korea', 'Singapore', 'Taiwan'],
            'ASEAN5 Economies': ['Indonesia', 'Malaysia', 'Philippines', 'Thailand', 'Vietnam'],
            'Asian EDMEs': ['Brunei', 'Cambodia', 'Laos', 'Mongolia', 'Nepal', 'Sri Lanka', 'Papua New Guinea', 'Myanmar'],
            'China': ['China'],
            'India': ['India'],
            }

df_temp_col_1

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,IIP: Assets,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,49.251410,55.400812,59.447361,67.574788,62.060306,58.531766,57.874145,55.339257,60.064708,63.971080,71.201661,NaN,NaN
2,IIP: Assets,China,15095.351337,15459.637344,15791.513791,17172.498955,19294.796530,18956.214763,18734.448489,18186.327382,18808.894045,18885.446752,19457.153153,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),11212.448000,11080.761196,11250.452559,12229.870692,12965.785227,12824.831873,12578.470956,11957.092472,12259.263950,12307.567071,12739.083520,NaN,NaN
4,IIP: Assets,India,1304.722689,1368.297282,1465.569636,1655.427998,1751.156057,1859.408122,1835.778114,1748.168061,1856.971906,1935.688768,2075.091003,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,IIP: Liabilities: Portfolio Investment: Equity,South Korea,937.516600,944.957200,812.291300,1182.292800,1415.169200,1275.668900,1033.044300,822.221000,1009.720900,1051.677100,1206.643700,NaN,NaN
585,IIP: Liabilities: Portfolio Investment: Equity,Sri Lanka,1.389949,2.031122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,IIP: Liabilities: Portfolio Investment: Equity,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,IIP: Liabilities: Portfolio Investment: Equity,Thailand,245.786189,236.186374,163.401446,164.705777,209.290300,194.279670,202.519460,196.886710,199.111530,181.182720,157.019100,NaN,NaN
588,IIP: Liabilities: Portfolio Investment: Equity,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_all_annual_2

,Type,Region,Unit,Last Update Time,2019-03-01 00:00:00,2019-06-01 00:00:00,2019-09-01 00:00:00,2019-12-01 00:00:00,2020-03-01 00:00:00,2020-06-01 00:00:00,...,2023-06-01 00:00:00,2023-09-01 00:00:00,2023-12-01 00:00:00,2024-03-01 00:00:00,2024-06-01 00:00:00,2024-09-01 00:00:00,2024-12-01 00:00:00,2025-03-01 00:00:00,2025-06-01 00:00:00,2025-09-01 00:00:00
0,IIP: Assets,Brunei,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,USD mn,2024-10-24,2.417597e+04,2.507544e+04,2.677201e+04,2.862880e+04,2.878970e+04,3.065766e+04,...,3.005370e+04,3.036972e+04,3.360136e+04,3.539776e+04,3.580391e+04,NaN,NaN,NaN,NaN,NaN
2,IIP: Assets,China,USD mn,2024-10-24,7.503297e+06,7.592054e+06,7.613220e+06,7.846418e+06,7.777337e+06,8.014177e+06,...,9.366431e+06,9.303764e+06,9.581683e+06,9.664292e+06,9.792861e+06,NaN,NaN,NaN,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),USD mn,2024-10-24,5.678545e+06,5.533903e+06,5.438994e+06,5.641767e+06,5.543582e+06,5.706870e+06,...,6.112216e+06,6.123758e+06,6.183809e+06,6.268514e+06,6.470570e+06,NaN,NaN,NaN,NaN,NaN
4,IIP: Assets,India,USD mn,2024-10-24,6.421384e+05,6.625843e+05,6.702019e+05,6.980954e+05,7.168001e+05,7.487695e+05,...,9.407915e+05,9.440507e+05,9.916381e+05,1.026863e+06,1.048228e+06,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584,IIP: Liabilities: Portfolio Investment: Equity,South Korea,USD mn,2024-09-26,4.697642e+05,4.677524e+05,4.474341e+05,4.975231e+05,3.733060e+05,4.389853e+05,...,5.192382e+05,4.861519e+05,5.655252e+05,5.988869e+05,6.077568e+05,NaN,NaN,NaN,NaN,NaN
585,IIP: Liabilities: Portfolio Investment: Equity,Sri Lanka,USD mn,2020-08-27,7.385835e+02,6.513650e+02,9.751852e+02,1.055937e+03,1.990319e+02,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,IIP: Liabilities: Portfolio Investment: Equity,Taiwan,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,IIP: Liabilities: Portfolio Investment: Equity,Thailand,USD mn,2024-10-24,1.182496e+05,1.275366e+05,1.200384e+05,1.161480e+05,7.432922e+04,8.907222e+04,...,9.603894e+04,9.113267e+04,9.005005e+04,8.106438e+04,7.595472e+04,NaN,NaN,NaN,NaN,NaN
588,IIP: Liabilities: Portfolio Investment: Equity,Vietnam,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.concat([df_temp_col_1[df_temp_col_1.columns[:2]][(df_temp_col_1['Type']=='IIP: Assets')], df_temp_col_1[df_temp_col_1.columns[2:]][(df_temp_col_1['Type']=='IIP: Assets')]/1000], axis=1)

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,IIP: Assets,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,0.049251,0.055401,0.059447,0.067575,0.062060,0.058532,0.057874,0.055339,0.060065,0.063971,0.071202,NaN,NaN
2,IIP: Assets,China,15.095351,15.459637,15.791514,17.172499,19.294797,18.956215,18.734448,18.186327,18.808894,18.885447,19.457153,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),11.212448,11.080761,11.250453,12.229871,12.965785,12.824832,12.578471,11.957092,12.259264,12.307567,12.739084,NaN,NaN
4,IIP: Assets,India,1.304723,1.368297,1.465570,1.655428,1.751156,1.859408,1.835778,1.748168,1.856972,1.935689,2.075091,NaN,NaN
5,IIP: Assets,Indonesia,0.724324,0.742283,0.750765,0.795300,0.825886,0.862788,0.869213,0.889769,0.931945,0.949373,0.977144,NaN,NaN
6,IIP: Assets,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,IIP: Assets,Malaysia,0.847109,0.855538,0.871443,0.925038,0.973585,1.005236,0.995476,0.987248,1.029305,1.035196,1.060096,NaN,NaN
8,IIP: Assets,Mongolia,0.013430,0.014119,0.014048,0.015230,0.016772,0.016180,0.013312,0.013112,0.014918,0.016978,0.017907,NaN,NaN
9,IIP: Assets,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,IIP: Assets,Nepal,0.019477,0.020144,0.022307,0.026409,0.025878,0.022840,0.021159,0.021425,0.024302,NaN,NaN,NaN,NaN
11,IIP: Assets,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,IIP: Assets,Philippines,0.371129,0.387572,0.404810,0.452345,0.464280,0.479457,0.468781,0.450068,0.469629,0.475559,0.488274,NaN,NaN
13,IIP: Assets,Singapore,8.108652,8.493461,8.830425,9.617985,10.106776,10.301273,10.430777,10.381529,10.761805,11.027629,11.384588,NaN,NaN
14,IIP: Assets,South Korea,3.244444,3.378478,3.443196,3.803669,4.127257,4.378646,4.421323,4.360306,4.514950,4.578736,4.767737,NaN,NaN
15,IIP: Assets,Sri Lanka,0.027092,0.025914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,IIP: Assets,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IIP: Assets,Thailand,1.023743,1.068453,1.106302,1.189434,1.207889,1.219443,1.202522,1.153967,1.193595,1.194805,1.220727,NaN,NaN
18,IIP: Assets,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_temp_col_1[(df_temp_col_1['Type']=='IIP: Assets')]

,Type,Region,1H2019,2H2019,1H2020,2H2020,1H2021,2H2021,1H2022,2H2022,1H2023,2H2023,1H2024,2H2024,1H2025
0,IIP: Assets,Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IIP: Assets,Cambodia,49.251410,55.400812,59.447361,67.574788,62.060306,58.531766,57.874145,55.339257,60.064708,63.971080,71.201661,NaN,NaN
2,IIP: Assets,China,15095.351337,15459.637344,15791.513791,17172.498955,19294.796530,18956.214763,18734.448489,18186.327382,18808.894045,18885.446752,19457.153153,NaN,NaN
3,IIP: Assets,Hong Kong SAR (China),11212.448000,11080.761196,11250.452559,12229.870692,12965.785227,12824.831873,12578.470956,11957.092472,12259.263950,12307.567071,12739.083520,NaN,NaN
4,IIP: Assets,India,1304.722689,1368.297282,1465.569636,1655.427998,1751.156057,1859.408122,1835.778114,1748.168061,1856.971906,1935.688768,2075.091003,NaN,NaN
5,IIP: Assets,Indonesia,724.323817,742.283316,750.764564,795.300483,825.885523,862.788313,869.213043,889.768871,931.945167,949.372809,977.144050,NaN,NaN
6,IIP: Assets,Laos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,IIP: Assets,Malaysia,847.108568,855.537747,871.443380,925.038211,973.584626,1005.236130,995.475752,987.248425,1029.305168,1035.195587,1060.095770,NaN,NaN
8,IIP: Assets,Mongolia,13.429910,14.118793,14.048275,15.229968,16.772060,16.179695,13.311752,13.111590,14.917649,16.977541,17.906857,NaN,NaN
9,IIP: Assets,Myanmar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,IIP: Assets,Nepal,19.477411,20.144181,22.306943,26.408513,25.877809,22.840498,21.159289,21.425242,24.302349,NaN,NaN,NaN,NaN
11,IIP: Assets,Papua New Guinea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,IIP: Assets,Philippines,371.128762,387.571664,404.810398,452.345429,464.279759,479.457113,468.781182,450.068182,469.628998,475.558780,488.273864,NaN,NaN
13,IIP: Assets,Singapore,8108.651714,8493.461121,8830.424645,9617.984644,10106.775691,10301.273054,10430.776740,10381.529413,10761.805293,11027.628917,11384.588361,NaN,NaN
14,IIP: Assets,South Korea,3244.443647,3378.477662,3443.196033,3803.668909,4127.256536,4378.645920,4421.323445,4360.306353,4514.950047,4578.735634,4767.737438,NaN,NaN
15,IIP: Assets,Sri Lanka,27.091998,25.913793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,IIP: Assets,Taiwan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IIP: Assets,Thailand,1023.743412,1068.453423,1106.302304,1189.434236,1207.888515,1219.443495,1202.521711,1153.966801,1193.594784,1194.804826,1220.726579,NaN,NaN
18,IIP: Assets,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_init

,group,short_title,desc
0,FDI Assets,FDI Assets,IIP: Assets: Direct Investment
1,FDI Assets,FDI Equity Assets,IIP: Assets: Direct Investment: Equity
2,FDI Assets,FDI Debt Assets,IIP: Assets: Direct Investment: Debt Instruments
3,Portfolio Assets,Portfolio Assets,IIP: Assets: Portfolio Investment
4,Portfolio Assets,Portfolio Equity Assets,IIP: Assets: Portfolio Investment: Equity
5,Portfolio Assets,Portfolio Debt Assets,IIP: Assets: Portfolio Investment: Debt Securi...
6,Financial Derivative Assets,Financial Derivative Assets,IIP: Assets: Financial Derivatives & Employee ...
7,Other Investment Assets,Other Investment Assets,IIP: Assets: Other Investment
8,Other Investment Assets,OI Equity Assets,IIP: Assets: Other Investment: Other Equity
9,Other Investment Assets,Currency and Deposits Assets,IIP: Assets: Other Investment: Currency & Depo...
10,Other Investment Assets,Loans Assets,IIP: Assets: Other Investment: Loans
11,Other Investment Assets,Insurance and Pension Assets,"IIP: Assets: Other Investment: Insurance, Pens..."
12,Other Investment Assets,Trade Credits and Advances Assets,IIP: Assets: Other Investment: Trade Credit & ...
13,Other Investment Assets,OI Others Assets,IIP: Assets: Other Investment: Other Accounts ...
14,Official Reserve Assets,Official Reserve Assets,IIP: Assets: Official Reserve Assets
15,International Investment Assets,International Investment Assets,IIP: Assets
16,FDI Liabilities,FDI Liabilities,IIP: Liabilities: Direct Investment
17,FDI Liabilities,FDI Equity Liabilities,IIP: Liabilities: Direct Investment: Equity
18,FDI Liabilities,FDI Debt Liabilities,IIP: Liabilities: Direct Investment: Debt Inst...
19,Portfolio Liabilities,Portfolio Liabilities,IIP: Liabilities: Portfolio Investment
20,Portfolio Liabilities,Portfolio Equity Liabilities,IIP: Liabilities: Portfolio Investment: Equity
21,Portfolio Liabilities,Portfolio Debt Liabilities,IIP: Liabilities: Portfolio Investment: Debt S...
22,Financial Derivative Liabilities,Financial Derivative Liabilities,IIP: Liabilities: Financial Derivatives & Empl...
23,Other Investment Liabilities,Other Investment Liabilities,IIP: Liabilities: Other Investment
24,Other Investment Liabilities,OI Equity Liabilities,IIP: Liabilities: Other Investment: Other Equity
25,Other Investment Liabilities,Currency and Deposits Liabilities,IIP: Liabilities: Other Investment: Currency &...
26,Other Investment Liabilities,Loans Liabilities,IIP: Liabilities: Other Investment: Loans
27,Other Investment Liabilities,Insurance and Pension Liabilities,"IIP: Liabilities: Other Investment: Insurance,..."
28,Other Investment Liabilities,Trade Credits and Advances Liabilities,IIP: Liabilities: Other Investment: Trade Cred...
29,Other Investment Liabilities,OI Others Liabilities,IIP: Liabilities: Other Investment: Other Acco...
30,Official Reserve Liabilities,Official Reserve Liabilities,IIP: Liabilities: Other Investment: SDRs
31,International Investment Liabilities,International Investment Liabilities,IIP: Liabilities

In [ ]:
###################### this is for equity ######################

asset_row = df_init.iloc[[0,4,5,6, 8, 9,10,11,12,13,14]]['desc'].to_list()
asset_row2 = ['Direct Investment', 'Portfolio Equity', 'Portfolio Debt','Financial Derivatives', 'Other Equity','Currency & Deposits','Loans','Insurance, Pension & Standardized Guarantee Schemes'
            ,'Trade Credit & Advances','Other Accounts Receivable','Reserve Assets', ]
sum_rows = df_init[(df_init['short_title'].isin(['OI Equity Assets','Insurance and Pension Assets','OI Others Assets',]))]['desc'].to_list()
order = ['Direct Investment','Portfolio Equity','Portfolio Debt','Financial Derivatives','Currency & Deposits','Loans','Trade Credit & Advances','Other Investments','Reserve Assets',]
df_by_region_main = pd.DataFrame(columns=df_temp_col_1.columns)

for x,y in calc_dict.items():
    # print(x,y)
    df_by_region_temp = df_temp_col_1[(df_temp_col_1['Region'].isin(y)) & (df_temp_col_1['Type'].isin(asset_row))]
    df_by_region_temp = df_by_region_temp.groupby(['Type']).sum()
    df_by_region_temp.loc[str(x) + ' Total'] = df_by_region_temp.sum()
    df_by_region_temp.loc['Other Investments'] = df_by_region_temp.loc[sum_rows].sum()
    df_by_region_temp.reset_index(inplace = True)
    df_by_region_temp = df_by_region_temp[(~df_by_region_temp['Type'].isin(sum_rows))] #####  the symbol of '~' use similar like notin, the oposite of isin. this is build in python operator
    df_by_region_temp['Type'] = df_by_region_temp['Type'].replace(asset_row, asset_row2)
    df_by_region_temp = df_by_region_temp.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(order)}))
    df_by_region_temp['Region'] = x

    df_by_region_main = pd.concat([df_by_region_main, df_by_region_temp], axis = 0)  


df_by_region_main.reset_index(inplace = True, drop=True)
df_by_region_main.insert(loc=0, column='Group', value='Assets')

###################### this is for equity ######################

###################### this is for debt ######################

debt_row = df_init.iloc[[20,24,25,26,28,29,30,31,32,33,34]]['desc'].to_list()
debt_row2 = ['Direct Investment', 'Portfolio Equity', 'Portfolio Debt','Financial Derivatives', 'Other Equity','Currency & Deposits','Loans','Insurance, Pension & Standardized Guarantee Schemes'
            ,'Trade Credit & Advances','Other Accounts Payable','SDR Liabilities', ]
sum_rows2 = df_init[(df_init['short_title'].isin(['OI Equity Liabilities', 'Insurance and Pension Liabilities', 'OI Others Liabilities', 'SDR Liabilities']))]['desc'].to_list()
order2 = ['Direct Investment','Portfolio Equity','Portfolio Debt','Financial Derivatives','Currency & Deposits','Loans','Trade Credit & Advances','Other Investments']
df_by_region_main2 = pd.DataFrame(columns=df_temp_col_1.columns)

for x,y in calc_dict.items():
    # print(x,y)
    df_by_region_temp = df_temp_col_1[(df_temp_col_1['Region'].isin(y)) & (df_temp_col_1['Type'].isin(debt_row))]
    df_by_region_temp = df_by_region_temp.groupby(['Type']).sum()
    df_by_region_temp.loc[str(x) + ' Total'] = df_by_region_temp.sum()
    df_by_region_temp.loc['Other Investments'] = df_by_region_temp.loc[sum_rows2].sum()
    df_by_region_temp.reset_index(inplace = True)
    df_by_region_temp = df_by_region_temp[(~df_by_region_temp['Type'].isin(sum_rows2))] #####  the symbol of '~' use similar like notin, the oposite of isin. this is build in python operator
    df_by_region_temp['Type'] = df_by_region_temp['Type'].replace(debt_row, debt_row2)
    df_by_region_temp = df_by_region_temp.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(order2)}))
    df_by_region_temp['Region'] = x

    df_by_region_main2 = pd.concat([df_by_region_main2, df_by_region_temp], axis = 0)  

df_by_region_main2.reset_index(inplace = True, drop=True)
df_by_region_main2.insert(loc=0, column='Group', value='Liabilities')

###################### this is for debt ######################

###################### this is for caq data ######################

caq_data = df_temp_col_1[(df_temp_col_1['Type'].isin(df_init[(df_init['group'] == 'Current Account')]['desc'].to_list()[1:]))]
caq_data_calc = caq_data.groupby(['Type']).sum()
caq_data_calc.loc['Current Account Balance'] = caq_data_calc.sum()
caq_data_calc['Region'] = 'Asia-Pacific'
caq_data_calc.reset_index(inplace=True)
rename_to = ['Goods Trade', 'Services Trade','Primary Income','Secondary Income',]
rename_from = ['BoP: Current Account: Goods','BoP: Current Account: Services','BoP: Current Account: Primary Income','BoP: Current Account: Secondary Income',]
caq_data_calc['Type'] = caq_data_calc['Type'].replace(rename_from, rename_to)
caq_data_calc = caq_data_calc.sort_values(by='Type', key=lambda x: x.map({k:i for i, k in enumerate(rename_to)}))
caq_data_calc.reset_index(drop=True, inplace=True)
caq_data_calc.insert(loc=0, column='Group', value='Current Account')

###################### this is for caq data ######################

df_main = pd.concat([df_by_region_main, df_by_region_main2, caq_data_calc], axis = 0) ## combine
df_main.reset_index(drop=True, inplace=True)

df_temp_col_1, df_all_annual_2, df_main